[2021-01-21 21:57:26,769] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_task 2021-01-20T00:00:00+00:00 [queued]>
[2021-01-21 21:57:26,774] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_task 2021-01-20T00:00:00+00:00 [queued]>
[2021-01-21 21:57:26,774] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 21:57:26,774] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-21 21:57:26,774] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 21:57:26,783] {taskinstance.py:1038} INFO - Executing <Task(SubDagOperator): processing_task> on 2021-01-20T00:00:00+00:00
[2021-01-21 21:57:26,785] {standard_task_runner.py:51} INFO - Started process 33499 to run task
[2021-01-21 21:57:26,789] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'processing_task', '2021-01-20T00:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmp8d_9qo57']
[2021-01-21 21:57:26,789] {standard_task_runner.py:76} INFO - Job 4: Subtask processing_task
[2021-01-21 21:57:26,818] {logging_mixin.py:103} INFO - Running <TaskInstance: parallel_dag.processing_task 2021-01-20T00:00:00+00:00 [running]> on host ip-172-31-18-6.ap-south-1.compute.internal
[2021-01-21 21:57:26,840] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=processing_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-20T00:00:00+00:00
[2021-01-21 21:57:26,852] {subdag.py:157} INFO - Created DagRun: scheduled__2021-01-20T00:00:00+00:00
[2021-01-21 22:01:02,769] {process_utils.py:95} INFO - Sending Signals.SIGTERM to GPID 33499
[2021-01-21 22:01:02,769] {taskinstance.py:1214} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-01-21 22:01:02,773] {taskinstance.py:1396} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/airflow_udemy/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/ubuntu/anaconda3/envs/airflow_udemy/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/ubuntu/anaconda3/envs/airflow_udemy/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/ubuntu/anaconda3/envs/airflow_udemy/lib/python3.7/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/ubuntu/anaconda3/envs/airflow_udemy/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1216, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-01-21 22:01:02,774] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=parallel_dag, task_id=processing_task, execution_date=20210120T000000, start_date=20210121T215726, end_date=20210121T220102
[2021-01-21 22:01:02,796] {process_utils.py:61} INFO - Process psutil.Process(pid=33499, status='terminated', exitcode=1, started='21:57:26') (33499) terminated with exit code 1
[2021-01-21 22:05:24,664] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_task 2021-01-20T00:00:00+00:00 [queued]>
[2021-01-21 22:05:24,696] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing_task 2021-01-20T00:00:00+00:00 [queued]>
[2021-01-21 22:05:24,696] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 22:05:24,696] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-21 22:05:24,697] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 22:05:24,721] {taskinstance.py:1038} INFO - Executing <Task(SubDagOperator): processing_task> on 2021-01-20T00:00:00+00:00
[2021-01-21 22:05:24,723] {standard_task_runner.py:51} INFO - Started process 36840 to run task
[2021-01-21 22:05:24,744] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'processing_task', '2021-01-20T00:00:00+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmpt5eqp7cg']
[2021-01-21 22:05:24,744] {standard_task_runner.py:76} INFO - Job 13: Subtask processing_task
[2021-01-21 22:05:24,875] {logging_mixin.py:103} INFO - Running <TaskInstance: parallel_dag.processing_task 2021-01-20T00:00:00+00:00 [running]> on host ip-172-31-18-6.ap-south-1.compute.internal
[2021-01-21 22:05:24,962] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=processing_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-20T00:00:00+00:00
[2021-01-21 22:05:25,030] {subdag.py:157} INFO - Created DagRun: scheduled__2021-01-20T00:00:00+00:00
[2021-01-21 22:06:25,120] {base.py:245} INFO - Success criteria met. Exiting.
[2021-01-21 22:06:25,132] {subdag.py:171} INFO - Execution finished. State is success
[2021-01-21 22:06:25,142] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=processing_task, execution_date=20210120T000000, start_date=20210121T220524, end_date=20210121T220625
[2021-01-21 22:06:25,177] {taskinstance.py:1195} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-01-21 22:06:25,199] {local_task_job.py:118} INFO - Task exited with return code 0
