[2021-01-21 22:10:32,218] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2021-01-21T22:10:23.461232+00:00 [queued]>
[2021-01-21 22:10:32,234] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2021-01-21T22:10:23.461232+00:00 [queued]>
[2021-01-21 22:10:32,234] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 22:10:32,234] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-21 22:10:32,234] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-21 22:10:32,241] {taskinstance.py:1038} INFO - Executing <Task(BashOperator): task_4> on 2021-01-21T22:10:23.461232+00:00
[2021-01-21 22:10:32,244] {standard_task_runner.py:51} INFO - Started process 74167 to run task
[2021-01-21 22:10:32,248] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2021-01-21T22:10:23.461232+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dags.py', '--cfg-path', '/tmp/tmpz86bnm5_']
[2021-01-21 22:10:32,249] {standard_task_runner.py:76} INFO - Job 24: Subtask task_4
[2021-01-21 22:10:32,295] {logging_mixin.py:103} INFO - Running <TaskInstance: parallel_dag.task_4 2021-01-21T22:10:23.461232+00:00 [running]> on host ip-172-31-18-6.ap-south-1.compute.internal
[2021-01-21 22:10:32,372] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2021-01-21T22:10:23.461232+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-21T22:10:23.461232+00:00
[2021-01-21 22:10:32,373] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-01-21 22:10:32,374] {bash.py:158} INFO - Running command: sleep 3
[2021-01-21 22:10:32,380] {bash.py:169} INFO - Output:
[2021-01-21 22:10:35,381] {bash.py:177} INFO - Command exited with return code 0
[2021-01-21 22:10:35,412] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20210121T221023, start_date=20210121T221032, end_date=20210121T221035
[2021-01-21 22:10:35,440] {taskinstance.py:1195} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-01-21 22:10:35,472] {local_task_job.py:118} INFO - Task exited with return code 0
